trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: gitversion/setup@0
      displayName: 'Install GitVersion Tool'
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: 'Get Semantic Version'
      inputs:
        useConfigFile: true
        configFilePath: './gitversion.yml'
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      displayName: 'Restore NuGets for solution'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'
        vstsFeed: 'd4d4328d-23fb-4700-a85b-694186019d4e/5bee72dc-d135-4e9c-84ec-df7c2fe16086'
        versioningScheme: byBuildNumber

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud (Vita)'
        organization: 'vita'
        scannerMode: 'MSBuild'
        projectKey: 'DiegoArranzGarcia_Vita.Core'
        projectName: 'Vita.Core'
    
    - task: VSBuild@1
      displayName: 'Compile Solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: DotNetCoreCLI@2
      displayName: 'Generate Vita.Common.nugpkg'
      inputs:
        command: 'pack'
        packagesToPack: '**/Vita.Common.csproj'
        nobuild: true
        includesymbols: false
        includesource: false
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion

    - task: DotNetCoreCLI@2
      displayName: 'Generate Vita.Core.Domain.nugpkg'
      inputs:
        command: 'pack'
        packagesToPack: '**/Vita.Core.Domain.csproj'
        nobuild: true
        includesymbols: false
        includesource: false
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion

    - task: DotNetCoreCLI@2
      displayName: 'Generate Vita.Core.Infrastructure.Sql.nugpkg'
      inputs:
        command: 'pack'
        packagesToPack: '**/Vita.Core.Infrastructure.Sql.csproj'
        nobuild: true
        includesymbols: false
        includesource: false
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion

    - task: DotNetCoreCLI@2
      displayName: 'Generate Vita.Core.Infrastructure.AzureServiceBus.nugpkg'
      inputs:
        command: 'pack'
        packagesToPack: '**/Vita.Core.Infrastructure.AzureServiceBus.csproj'
        nobuild: true
        includesymbols: false
        includesource: false
        versioningScheme: byEnvVar 
        versionEnvVar: GitVersion.NuGetVersion
    
    - task: DotNetCoreCLI@2
      displayName: 'Push NuGet Packages'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'd4d4328d-23fb-4700-a85b-694186019d4e/5bee72dc-d135-4e9c-84ec-df7c2fe16086'
        versioningScheme: byBuildNumber